[build]
  command = "echo ğŸ—"
  publish = "/deploy"
  base = "/"

[[redirects]]
  from = "https://a.scope42.org/*"
  to = "/deploy/page-a/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://b.scope42.org/*"
  to = "/deploy/page-b/:splat"
  status = 200
  force = true
